### ISSUE TITLE
When editing comments, special characters get escaped

### ISSUE THREAD

**Issue by Gewi413** [p2r3/epochtal#93] opened 2024-08-24 19:03 UTC
Expected behavior: when clicking edit, the same comment which is shown when hovering is shown to edit

Actual: ![image](https://github.com/user-attachments/assets/738fccaa-7968-49c3-95c0-a04e5a4cb210)

**Comment by rudkoLA** [comment] 2024-08-24 19:11
Duplicate of #84

**Closed** 2024-08-24 19:14 UTC
